version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - 3002:80
    volumes:
      - ./nginx/conf/ghost.conf:/etc/nginx/conf.d/default.conf
    links:
      - ghost
    restart: always

  ghost:
    image: ghost:4-alpine
    container_name: ghost
    hostname: ghost
    volumes:
      - ./ghost/config.production.json:/var/lib/ghost/config.production.json
      - $PWD/ghost/content:/var/lib/ghost/content
    expose:
      - "3306"
    environment: # this section can be commented to start in dev mode by default
      - url=http://localhost:3002
      - NODE_ENV=production # set either production or development, then it will load the respective config
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./dbdata:/var/lib/mysql # Persist storage
    expose:
      - "3306"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      - MYSQL_ROOT_PASSWORD=Admin123@
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev #please change this
    restart: always
